### ISSUE TITLE
Latest players blocked overwiev

### ISSUE THREAD

**Issue by Baxuriuks** [brhndursun/SourceBans-StarTheme#1]
When you click on a player in the "Latest Players Blocked" overwiev the info doesn't showing up. It does work on "Latest Comm Blocks" . If I enable default theme then everything is ok.

**Comment by brhndursun** [comment]
I've fixed the issue. Will you please test it and let me know if its working.

Badge and Popup Fix: https://github.com/brhndursun/SourceBans-StarTheme/commit/f950b07527bdd8e01bb7898f271c6bc03cfbd002

**Comment by Baxuriuks** [comment]
Looks like it's working OK now. Thank You.
