### ISSUE TITLE
Where are the sidebar labels located?

### ISSUE THREAD

**Issue by WilliamNT** [brhndursun/SourceBans-StarTheme#18]
Hi! I am translating the website for our server but I am struggling with finding the [sidebar](https://prnt.sc/VTP0qdcydzlj) labels' locations. Can you point me in the right direction please?

**Comment by distratul** [comment]
They are located in Main Folder, in Includes, and then in system-functions.php line 147 and 182.

**Comment by GLUNAX** [comment]
Thanks alot 👍
