### ISSUE TITLE
Bug Rcon

### ISSUE THREAD

**Issue by ThanhByKyTa** [brhndursun/SourceBans-StarTheme#2]
![image](https://user-images.githubusercontent.com/33537916/50043024-8accfa00-009f-11e9-8fa5-19304eb7bc4c.png)

Lag rcon

**Comment by paulocrash** [comment]
He is already inside the BUG, ​​already informed to him...

http://prntscr.com/lvpxhf

**Comment by brhndursun** [comment]
Rcon has been fixed but not released. You can test it by downloading zip from main repo page. 

[Master Archive ZIP](https://github.com/brhndursun/SourceBans-StarTheme/archive/master.zip)

https://github.com/brhndursun/SourceBans-StarTheme/commit/69a756c423ce01125c9e892fa09b637c38ceaf5a

https://i.ibb.co/V3DNKXg/rcon.jpg
