### ISSUE TITLE
Blank screen.

### ISSUE THREAD

**Issue by uwejan** [brhndursun/SourceBans-StarTheme#4]
Hello, i just installed the star theme, my screen became white, so i removed the theme dir of star, from themes dir, then copied the original theme as star and modified the php file  defining star as theme name, now am getting blank page with this error, 
`Theme Error: star is not a valid theme. Must have a valid theme.conf.php file.
`, help appreciated.

**Comment by brhndursun** [comment]
Copy my theme.conf.php file to your duplicated original theme folder and dont forget to change coppied theme folder name to star as exactly same as my theme.
Another way to solve this issue is in db. Change theme name to default in settings table

**Comment by brhndursun** [comment]
Hope you fixed the issue. Also I'd like to help you about installing my theme if you want.
