### ISSUE TITLE
Templates error

### ISSUE THREAD

**Issue by GamerXCZ** [brhndursun/SourceBans-StarTheme#5]
When i activate star theme all pages get this error

> Fatal error: Uncaught Mustache_Exception_UnknownTemplateException: Unknown template: core/header in /var/www/bans/public_html/includes/Mustache/Loader/FilesystemLoader.php:102 Stack trace: #0 /var/www/bans/public_html/includes/Mustache/Loader/FilesystemLoader.php(82): Mustache_Loader_FilesystemLoader->loadFile('core/header') #1 /var/www/bans/public_html/includes/Mustache/Engine.php(657): Mustache_Loader_FilesystemLoader->load('core/header') #2 /var/www/bans/public_html/includes/Template.php(14): Mustache_Engine->loadTemplate('core/header') #3 /var/www/bans/public_html/pages/core/header.php(12): Template::render('core/header', Array) #4 /var/www/bans/public_html/includes/page-builder.php(130): require_once('/var/www/bans/p...') #5 /var/www/bans/public_html/index.php(37): build('SourceBans++ Se...', '/admin.settings...') #6 {main} thrown in /var/www/bans/public_html/includes/Mustache/Loader/FilesystemLoader.php on line 102

**Comment by brhndursun** [comment]
Works only v1.6.3
