### ISSUE TITLE
Problem with theme after login to sbpp no login method depends

### ISSUE THREAD

**Issue by Nerus87** [brhndursun/SourceBans-StarTheme#6]
**Describe the bug**
![Theme not loaded correctly after login](https://user-images.githubusercontent.com/3099926/52902236-868f9b00-320e-11e9-8bd4-bc67d888e88a.png)

Site is blank after login with this bar view only, before login no problems found.

**To Reproduce**
1. Go to 'site'
2. Login to the account 
3. See error

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser All
 - Version 1.6.3

**Additional context**
Nginx + SSL

**Comment by brhndursun** [comment]
You have to enable bcmath extensions in php.ini
It should be enabled in default settings. Hmm.... I've better try catch in photoget file..

**Comment by Nerus87** [comment]
Additional info:

> FastCGI sent in stderr: "PHP message: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/sourcebans/steamopenid.php on line 79" while reading response header from upstream, client: 83.6.92.159, server: www.sb.starewygi.pl

**Comment by brhndursun** [comment]
I dont have an idea about this issue. Maybe you should ask in sbpp github page. Also they are using new way to login with steam but theme is not available on new github version. As soon as new version has released, I will create new dark and light theme for it. Cheerz.
